### PR TITLE
Update to JWT RC2, handle expired tokens/bad signatures

### PR DESCRIPTION
**Pull request by racingcow**
Hi @jamiekurtz,

Thanks for the great project. I updated to the latest JWT prerelease package from Microsoft, and added some additional handling for both expired tokens, and tokens that were signed with untrusted certs.

@racingcow

### CODE REVIEW

**Comment by ronnieoverby** [comment]
I really don't like the 440 thing. I wish I could turn it off.

**Comment by racingcow** [comment]
@ronnieoverby ,

What would you prefer happen when a SecurityTokenExpiredException occurs? Just let the exception go? Return a 200? Something else?

**Comment by ronnieoverby** [comment]
Haha, no. 

440 is not a standard status code. See W3C or MDN. It's a Microsoft invention for OWA. That's not what bothers me about it.

The issue is the mental overhead that I have to suffer to implement handling this extra status code in my app. The end result of an expired JWT should be the same as it is under any other validation failure: a 401.

To quote the famous wizard Gandalf from his keynote speech at the Geneva Web Summit of 1943:

"Keep it simple, keep it standard, stupid."

**Comment by racingcow** [comment]
@ronnieoverby ,

Hmm. I need the 440 for a MS-heavy (which probably explains the non-standard 440) app. Maybe you could add a pull request with an option or something (with the default being both situations sending back a 401)? I suppose it's ultimately up to @jamiekurtz .

**Pull request merged**
